"use client";
import { Download } from "lucide-react";

export const DownloadSummaryButton = ({
  title,
  summary_text,
  created_at,
  file_name,
}: {
  title: string;
  summary_text: string;
  created_at: Date;
  file_name: string;
}) => {
  const handelDownload = () => {
    const summaryContent = `Title: ${title.slice(0, title.lastIndexOf("."))}
Generated Summary
Generated On: ${new Date(created_at).toLocaleDateString("en-US", {
      year: "numeric",
      month: "long",
      day: "numeric",
    })}
    ${summary_text}
Original File Name: ${file_name}
Generated by Quick Digest`;
    const blob = new Blob([summaryContent], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${file_name.slice(0, file_name.lastIndexOf("."))}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
  };
  return (
    <button
      className="h-8 px-3 text-indigo-300 hover:text-indigo-300 bg-neutral-900  hover:bg-neutral-800 cursor-pointer flex items-center gap-1.5 rounded-md"
      onClick={handelDownload}
    >
      <Download className="h-3 w-3 text-indigo-400" />
      Download Summary
    </button>
  );
};
